# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastnews', '0002_auto_20200615_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelike',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlelike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='article',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='uesr',
        ),
        migrations.RemoveField(
            model_name='usersubscribe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dislike_cnt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_cnt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike_cnt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_cnt',
        ),
        migrations.DeleteModel(
            name='ArticleLike',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserSubscribe',
        ),
    ]
